export const mockRecipes = [
  {
    id: '1',
    name: 'Avocado Toast',
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '10 min',
    cookTime: '5 min',
    servings: 1,
    calories: 320,
    protein: 12,
    carbs: 30,
    fat: 18,
    ingredients: [
      '2 slices whole grain bread',
      '1 ripe avocado',
      '2 eggs',
      'Salt and pepper to taste',
      'Red pepper flakes (optional)',
    ],
    instructions: [
      'Toast the bread until golden and firm.',
      'Remove the pit from the avocado and scoop the flesh into a bowl.',
      'Mash the avocado with a fork and season with salt and pepper.',
      'Spread the mashed avocado on top of the toasted bread.',
      'Fry the eggs to your liking and place on top of the avocado toast.',
      'Sprinkle with additional salt, pepper, and red pepper flakes if desired.',
    ],
    tags: ['breakfast', 'vegetarian', 'quick'],
  },
  {
    id: '2',
    name: 'Greek Salad',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '0 min',
    servings: 2,
    calories: 250,
    protein: 8,
    carbs: 15,
    fat: 20,
    ingredients: [
      '1 cucumber, diced',
      '2 large tomatoes, diced',
      '1 red onion, thinly sliced',
      '1 cup kalamata olives',
      '200g feta cheese, cubed',
      '2 tbsp olive oil',
      '1 tbsp red wine vinegar',
      '1 tsp dried oregano',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Combine cucumber, tomatoes, red onion, and olives in a large bowl.',
      'Add the feta cheese cubes.',
      'In a small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper.',
      'Pour the dressing over the salad and toss gently to combine.',
      'Serve immediately or refrigerate for up to 1 hour before serving.',
    ],
    tags: ['lunch', 'vegetarian', 'salad'],
  },
  {
    id: '3',
    name: 'Chicken Stir Fry',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '20 min',
    cookTime: '15 min',
    servings: 4,
    calories: 380,
    protein: 35,
    carbs: 25,
    fat: 15,
    ingredients: [
      '500g chicken breast, sliced',
      '2 bell peppers, sliced',
      '1 broccoli head, cut into florets',
      '1 carrot, julienned',
      '3 cloves garlic, minced',
      '1 tbsp ginger, grated',
      '3 tbsp soy sauce',
      '1 tbsp honey',
      '2 tbsp vegetable oil',
      '1 tsp sesame oil',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Heat vegetable oil in a large wok or skillet over high heat.',
      'Add chicken and cook until browned, about 5-6 minutes. Remove and set aside.',
      'In the same pan, add a bit more oil if needed, then add garlic and ginger. Stir for 30 seconds.',
      'Add all vegetables and stir fry for 5-6 minutes until crisp-tender.',
      'Return chicken to the pan. Add soy sauce and honey, stirring to coat everything.',
      'Cook for another 2 minutes until everything is heated through.',
      'Drizzle with sesame oil, season with salt and pepper, and serve hot.',
    ],
    tags: ['dinner', 'high-protein', 'asian'],
  },
  {
    id: '4',
    name: 'Overnight Oats with Berries',
    image: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 1,
    calories: 310,
    protein: 14,
    carbs: 45,
    fat: 8,
    ingredients: [
      '1/2 cup rolled oats',
      '1/2 cup almond milk',
      '1/4 cup Greek yogurt',
      '1 tbsp chia seeds',
      '1 tbsp honey or maple syrup',
      '1/2 cup mixed berries',
      '1 tbsp sliced almonds',
    ],
    instructions: [
      'In a jar or container, combine oats, almond milk, Greek yogurt, chia seeds, and honey.',
      'Stir well to combine all ingredients.',
      'Seal the container and refrigerate overnight or for at least 4 hours.',
      'Before serving, top with mixed berries and sliced almonds.',
    ],
    tags: ['breakfast', 'vegetarian', 'meal-prep', 'no-cook'],
  },
  {
    id: '5',
    name: 'Quinoa Buddha Bowl',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '20 min',
    servings: 2,
    calories: 420,
    protein: 15,
    carbs: 60,
    fat: 16,
    ingredients: [
      '1 cup quinoa, rinsed',
      '2 cups vegetable broth',
      '1 sweet potato, diced',
      '1 tbsp olive oil',
      '1 cup chickpeas, drained and rinsed',
      '1 tsp cumin',
      '1 avocado, sliced',
      '2 cups mixed greens',
      '1/4 cup tahini',
      '1 tbsp lemon juice',
      '1 tbsp water',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Cook quinoa in vegetable broth according to package instructions.',
      'Toss sweet potato with olive oil, salt, and pepper. Roast for 20 minutes until tender.',
      'Season chickpeas with cumin, salt, and pepper.',
      'Make dressing by whisking together tahini, lemon juice, water, salt, and pepper.',
      'Assemble bowls with quinoa, roasted sweet potato, chickpeas, avocado, and mixed greens.',
      'Drizzle with tahini dressing before serving.',
    ],
    tags: ['lunch', 'vegan', 'bowl', 'healthy'],
  },
  {
    id: '6',
    name: 'Salmon with Roasted Vegetables',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '25 min',
    servings: 2,
    calories: 450,
    protein: 35,
    carbs: 20,
    fat: 25,
    ingredients: [
      '2 salmon fillets (150g each)',
      '2 tbsp olive oil',
      '1 lemon, sliced',
      '2 cloves garlic, minced',
      '1 zucchini, sliced',
      '1 bell pepper, sliced',
      '1 red onion, sliced',
      '1 tbsp fresh dill, chopped',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Place salmon fillets on a baking sheet lined with parchment paper.',
      'In a bowl, toss vegetables with olive oil, garlic, salt, and pepper.',
      'Arrange vegetables around the salmon on the baking sheet.',
      'Top salmon with lemon slices and sprinkle with dill.',
      'Bake for 20-25 minutes until salmon is cooked through and vegetables are tender.',
      'Serve hot, garnished with additional fresh dill if desired.',
    ],
    tags: ['dinner', 'high-protein', 'seafood', 'low-carb'],
  },
  {
    id: '7',
    name: 'Vegetarian Chili',
    image: 'https://images.unsplash.com/photo-1564671546498-aa134722790f?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '45 min',
    servings: 6,
    calories: 320,
    protein: 15,
    carbs: 45,
    fat: 8,
    ingredients: [
      '1 onion, diced',
      '3 cloves garlic, minced',
      '1 red bell pepper, diced',
      '1 green bell pepper, diced',
      '2 carrots, diced',
      '2 cans (15 oz each) black beans, drained and rinsed',
      '1 can (15 oz) kidney beans, drained and rinsed',
      '1 can (28 oz) diced tomatoes',
      '2 cups vegetable broth',
      '2 tbsp chili powder',
      '1 tbsp cumin',
      '1 tsp oregano',
      '1/2 tsp cayenne pepper (optional)',
      'Salt and pepper to taste',
      'Toppings: avocado, cilantro, lime wedges, Greek yogurt',
    ],
    instructions: [
      'Heat olive oil in a large pot over medium heat.',
      'Add onion and garlic, sauté until fragrant, about 3 minutes.',
      'Add bell peppers and carrots, cook for 5 minutes until softened.',
      'Stir in beans, diced tomatoes, vegetable broth, and all spices.',
      'Bring to a boil, then reduce heat and simmer for 30-40 minutes, stirring occasionally.',
      'Taste and adjust seasonings as needed.',
      'Serve hot with your choice of toppings.',
    ],
    tags: ['dinner', 'vegetarian', 'vegan', 'meal-prep', 'high-fiber'],
  },
  {
    id: '8',
    name: 'Banana Protein Smoothie',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a90bb0ae?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 1,
    calories: 280,
    protein: 25,
    carbs: 30,
    fat: 8,
    ingredients: [
      '1 ripe banana',
      '1 cup almond milk',
      '1 scoop (25g) protein powder',
      '1 tbsp almond butter',
      '1/2 tsp cinnamon',
      '1/2 cup ice cubes',
      '1 tsp honey (optional)',
    ],
    instructions: [
      'Add all ingredients to a blender.',
      'Blend on high speed until smooth and creamy.',
      'Pour into a glass and serve immediately.',
    ],
    tags: ['breakfast', 'snack', 'high-protein', 'quick', 'no-cook'],
  },
  {
    id: '9',
    name: 'Mediterranean Stuffed Bell Peppers',
    image: 'https://images.unsplash.com/photo-1600335895229-6e75511892c8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '20 min',
    cookTime: '35 min',
    servings: 4,
    calories: 350,
    protein: 12,
    carbs: 40,
    fat: 16,
    ingredients: [
      '4 large bell peppers, tops removed and seeded',
      '1 cup quinoa, rinsed',
      '2 cups vegetable broth',
      '1 onion, diced',
      '2 cloves garlic, minced',
      '1 zucchini, diced',
      '1 cup cherry tomatoes, halved',
      '1/2 cup kalamata olives, pitted and chopped',
      '1/2 cup feta cheese, crumbled',
      '2 tbsp olive oil',
      '1 tsp dried oregano',
      '1/4 cup fresh parsley, chopped',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 375°F (190°C).',
      'Cook quinoa in vegetable broth according to package instructions.',
      'In a skillet, heat olive oil over medium heat. Add onion and garlic, sauté until fragrant.',
      'Add zucchini and cook for 3-4 minutes until softened.',
      'In a large bowl, combine cooked quinoa, sautéed vegetables, cherry tomatoes, olives, feta cheese, oregano, parsley, salt, and pepper.',
      'Stuff the bell peppers with the quinoa mixture and place in a baking dish.',
      'Cover with foil and bake for 25 minutes. Remove foil and bake for an additional 10 minutes.',
      'Serve hot, garnished with additional parsley if desired.',
    ],
    tags: ['dinner', 'vegetarian', 'mediterranean', 'meal-prep'],
  },
  {
    id: '10',
    name: 'Lemon Garlic Shrimp Pasta',
    image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '10 min',
    cookTime: '15 min',
    servings: 4,
    calories: 420,
    protein: 28,
    carbs: 50,
    fat: 14,
    ingredients: [
      '12 oz (340g) linguine pasta',
      '1 lb (450g) large shrimp, peeled and deveined',
      '4 cloves garlic, minced',
      '1/4 cup olive oil',
      '1/4 cup fresh lemon juice',
      '1 tsp lemon zest',
      '1/4 cup fresh parsley, chopped',
      '1/4 cup grated Parmesan cheese',
      '1/4 tsp red pepper flakes (optional)',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Cook pasta according to package instructions. Reserve 1/2 cup of pasta water before draining.',
      'In a large skillet, heat olive oil over medium-high heat.',
      'Add shrimp and cook for 2 minutes per side until pink and opaque. Remove and set aside.',
      'In the same skillet, add garlic and red pepper flakes. Sauté for 30 seconds until fragrant.',
      'Add lemon juice and zest, then return shrimp to the skillet.',
      'Add drained pasta and toss to combine. If needed, add reserved pasta water to loosen the sauce.',
      'Stir in parsley and Parmesan cheese. Season with salt and pepper.',
      'Serve immediately, garnished with additional Parmesan and parsley if desired.',
    ],
    tags: ['dinner', 'seafood', 'pasta', 'quick'],
  },
  {
    id: '11',
    name: 'Keto Bacon and Egg Cups',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '10 min',
    cookTime: '20 min',
    servings: 6,
    calories: 180,
    protein: 12,
    carbs: 1,
    fat: 14,
    ingredients: [
      '12 slices bacon',
      '12 large eggs',
      '1/2 cup cheddar cheese, shredded',
      '2 green onions, thinly sliced',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 375°F (190°C). Grease a 12-cup muffin tin.',
      'Line each muffin cup with a slice of bacon, creating a circle around the edge.',
      'Crack an egg into each bacon-lined cup.',
      'Sprinkle with salt, pepper, cheese, and green onions.',
      'Bake for 15-20 minutes until eggs are set to your liking.',
      'Let cool for a few minutes before removing from the muffin tin.',
      'Serve warm or refrigerate for a quick breakfast option throughout the week.',
    ],
    tags: ['breakfast', 'keto', 'low-carb', 'high-protein', 'meal-prep'],
  },
  {
    id: '12',
    name: 'Vegan Lentil Soup',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '35 min',
    servings: 6,
    calories: 250,
    protein: 14,
    carbs: 40,
    fat: 4,
    ingredients: [
      '2 cups dried green or brown lentils, rinsed',
      '1 onion, diced',
      '2 carrots, diced',
      '2 celery stalks, diced',
      '3 cloves garlic, minced',
      '1 can (14 oz) diced tomatoes',
      '6 cups vegetable broth',
      '2 bay leaves',
      '1 tsp cumin',
      '1 tsp paprika',
      '1/2 tsp turmeric',
      '1/4 cup fresh parsley, chopped',
      '1 tbsp lemon juice',
      'Salt and pepper to taste',
    ],
    instructions: [
      'In a large pot, heat olive oil over medium heat. Add onion, carrots, and celery. Sauté for 5 minutes.',
      'Add garlic and cook for another minute until fragrant.',
      'Stir in lentils, diced tomatoes, vegetable broth, bay leaves, cumin, paprika, and turmeric.',
      'Bring to a boil, then reduce heat and simmer, covered, for 25-30 minutes until lentils are tender.',
      'Remove bay leaves. For a creamier texture, blend a portion of the soup and return it to the pot.',
      'Stir in lemon juice and parsley. Season with salt and pepper to taste.',
      'Serve hot, garnished with additional parsley if desired.',
    ],
    tags: ['lunch', 'dinner', 'vegan', 'high-fiber', 'meal-prep'],
  },
  {
    id: '13',
    name: 'Caprese Chicken',
    image: 'https://images.unsplash.com/photo-1600335895229-6e75511892c8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '10 min',
    cookTime: '25 min',
    servings: 4,
    calories: 380,
    protein: 35,
    carbs: 8,
    fat: 22,
    ingredients: [
      '4 chicken breasts',
      '2 tbsp olive oil',
      '2 cloves garlic, minced',
      '1 tsp Italian seasoning',
      '2 large tomatoes, sliced',
      '8 oz fresh mozzarella, sliced',
      '1/4 cup fresh basil leaves',
      '2 tbsp balsamic glaze',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 375°F (190°C).',
      'Season chicken breasts with salt, pepper, and Italian seasoning.',
      'Heat olive oil in an oven-safe skillet over medium-high heat.',
      'Add chicken and sear for 3-4 minutes per side until golden brown.',
      'Add garlic around the chicken and cook for 30 seconds.',
      'Top each chicken breast with tomato slices, mozzarella, and a few basil leaves.',
      'Transfer skillet to the oven and bake for 15-18 minutes until chicken is cooked through.',
      'Drizzle with balsamic glaze before serving.',
    ],
    tags: ['dinner', 'high-protein', 'low-carb', 'italian'],
  },
  {
    id: '14',
    name: 'Sweet Potato Black Bean Burrito Bowl',
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '30 min',
    servings: 4,
    calories: 420,
    protein: 15,
    carbs: 65,
    fat: 12,
    ingredients: [
      '2 large sweet potatoes, diced',
      '1 tbsp olive oil',
      '1 tsp cumin',
      '1 tsp paprika',
      '1 can (15 oz) black beans, drained and rinsed',
      '1 cup corn kernels (fresh or frozen)',
      '1 cup cooked brown rice',
      '1 avocado, sliced',
      '1/4 cup red onion, diced',
      '1/4 cup cilantro, chopped',
      'Lime wedges for serving',
      'For the dressing:',
      '1/4 cup Greek yogurt',
      '2 tbsp lime juice',
      '1 clove garlic, minced',
      '1/2 tsp cumin',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Toss sweet potatoes with olive oil, cumin, paprika, salt, and pepper. Spread on a baking sheet.',
      'Roast for 25-30 minutes until tender and slightly crispy, stirring halfway through.',
      'Meanwhile, prepare the dressing by whisking together all dressing ingredients.',
      'In a small saucepan, heat black beans and corn until warmed through.',
      'Assemble bowls with brown rice, roasted sweet potatoes, black beans, corn, avocado, red onion, and cilantro.',
      'Drizzle with dressing and serve with lime wedges.',
    ],
    tags: ['lunch', 'dinner', 'vegetarian', 'vegan', 'bowl', 'meal-prep'],
  },
  {
    id: '15',
    name: 'Almond Flour Pancakes',
    image: 'https://images.unsplash.com/photo-1575853121743-60c24f0a7502?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '10 min',
    cookTime: '15 min',
    servings: 2,
    calories: 340,
    protein: 14,
    carbs: 12,
    fat: 28,
    ingredients: [
      '1 1/2 cups almond flour',
      '3 large eggs',
      '1/4 cup almond milk',
      '1 tbsp maple syrup',
      '1 tsp vanilla extract',
      '1/2 tsp baking powder',
      '1/4 tsp salt',
      '1 tbsp coconut oil for cooking',
      'Toppings: berries, banana slices, maple syrup, or nut butter',
    ],
    instructions: [
      'In a large bowl, whisk together almond flour, baking powder, and salt.',
      'In a separate bowl, beat eggs, then add almond milk, maple syrup, and vanilla extract.',
      'Pour wet ingredients into dry ingredients and stir until well combined.',
      'Heat coconut oil in a non-stick skillet over medium heat.',
      'Pour 1/4 cup of batter for each pancake. Cook for 2-3 minutes until bubbles form on the surface.',
      'Flip and cook for another 2 minutes until golden brown.',
      'Serve warm with your choice of toppings.',
    ],
    tags: ['breakfast', 'gluten-free', 'low-carb', 'keto'],
  },
  {
    id: '16',
    name: 'Beef and Broccoli Stir Fry',
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '15 min',
    servings: 4,
    calories: 380,
    protein: 30,
    carbs: 20,
    fat: 18,
    ingredients: [
      '1 lb (450g) flank steak, thinly sliced against the grain',
      '4 cups broccoli florets',
      '1 red bell pepper, sliced',
      '3 cloves garlic, minced',
      '1 tbsp ginger, grated',
      '3 tbsp vegetable oil',
      'For the sauce:',
      '1/3 cup low-sodium soy sauce',
      '1/4 cup beef broth',
      '2 tbsp brown sugar',
      '1 tbsp cornstarch',
      '1 tsp sesame oil',
      'Red pepper flakes to taste',
    ],
    instructions: [
      'In a small bowl, whisk together all sauce ingredients and set aside.',
      'Heat 1 tbsp oil in a large wok or skillet over high heat.',
      'Add beef and cook for 2-3 minutes until browned. Remove and set aside.',
      'Add remaining oil to the pan. Add broccoli and bell pepper, stir fry for 4-5 minutes.',
      'Add garlic and ginger, cook for 30 seconds until fragrant.',
      'Return beef to the pan. Pour in the sauce and stir to combine.',
      'Cook for 2-3 minutes until sauce thickens and everything is well coated.',
      'Serve hot over rice or cauliflower rice.',
    ],
    tags: ['dinner', 'high-protein', 'asian', 'quick'],
  },
  {
    id: '17',
    name: 'Mediterranean Chickpea Salad',
    image: 'https://images.unsplash.com/photo-1511357840105-cde01bdc7be8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '0 min',
    servings: 4,
    calories: 280,
    protein: 10,
    carbs: 30,
    fat: 15,
    ingredients: [
      '2 cans (15 oz each) chickpeas, drained and rinsed',
      '1 cucumber, diced',
      '1 bell pepper, diced',
      '1/2 red onion, finely diced',
      '1 cup cherry tomatoes, halved',
      '1/2 cup kalamata olives, pitted and halved',
      '1/2 cup feta cheese, crumbled',
      '1/4 cup fresh parsley, chopped',
      'For the dressing:',
      '1/4 cup olive oil',
      '2 tbsp lemon juice',
      '1 clove garlic, minced',
      '1 tsp dried oregano',
      'Salt and pepper to taste',
    ],
    instructions: [
      'In a large bowl, combine chickpeas, cucumber, bell pepper, red onion, cherry tomatoes, olives, feta cheese, and parsley.',
      'In a small bowl, whisk together all dressing ingredients.',
      'Pour dressing over the salad and toss gently to combine.',
      'Refrigerate for at least 30 minutes before serving to allow flavors to meld.',
      'Serve chilled as a main dish or side salad.',
    ],
    tags: ['lunch', 'vegetarian', 'mediterranean', 'no-cook', 'meal-prep'],
  },
  {
    id: '18',
    name: 'Cauliflower Fried Rice',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '15 min',
    servings: 4,
    calories: 220,
    protein: 12,
    carbs: 15,
    fat: 12,
    ingredients: [
      '1 large cauliflower head, riced',
      '2 tbsp sesame oil',
      '2 eggs, beaten',
      '1 onion, diced',
      '2 carrots, diced',
      '1 cup frozen peas',
      '3 cloves garlic, minced',
      '1 tbsp ginger, grated',
      '3 tbsp soy sauce',
      '1 tbsp rice vinegar',
      '2 green onions, sliced',
      '2 tbsp cilantro, chopped',
    ],
    instructions: [
      'Heat 1 tbsp sesame oil in a large skillet or wok over medium-high heat.',
      'Add beaten eggs and scramble until cooked through. Remove and set aside.',
      'Add remaining oil to the pan. Add onion and carrots, sauté for 3-4 minutes.',
      'Add garlic and ginger, cook for 30 seconds until fragrant.',
      'Add cauliflower rice and peas. Stir fry for 5-6 minutes until cauliflower is tender.',
      'Return eggs to the pan. Add soy sauce and rice vinegar, stir to combine.',
      'Cook for another 2 minutes until everything is heated through.',
      'Garnish with green onions and cilantro before serving.',
    ],
    tags: ['dinner', 'low-carb', 'keto', 'asian', 'vegetarian'],
  },
  {
    id: '19',
    name: 'Peanut Butter Banana Smoothie Bowl',
    image: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 1,
    calories: 380,
    protein: 15,
    carbs: 50,
    fat: 16,
    ingredients: [
      '2 frozen bananas',
      '2 tbsp peanut butter',
      '1/2 cup almond milk',
      '1 tbsp honey or maple syrup',
      '1/2 tsp vanilla extract',
      'Toppings:',
      '1/4 cup granola',
      '1 tbsp chia seeds',
      'Fresh berries',
      'Sliced banana',
      'Drizzle of peanut butter',
    ],
    instructions: [
      'In a blender, combine frozen bananas, peanut butter, almond milk, honey, and vanilla extract.',
      'Blend until smooth and creamy. The mixture should be thicker than a regular smoothie.',
      'Pour into a bowl and add toppings as desired.',
      'Serve immediately.',
    ],
    tags: ['breakfast', 'vegetarian', 'no-cook', 'high-fiber'],
  },
  {
    id: '20',
    name: 'Baked Cod with Lemon and Herbs',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '10 min',
    cookTime: '20 min',
    servings: 4,
    calories: 220,
    protein: 35,
    carbs: 5,
    fat: 8,
    ingredients: [
      '4 cod fillets (150g each)',
      '2 tbsp olive oil',
      '2 cloves garlic, minced',
      '1 lemon, thinly sliced',
      '2 tbsp fresh parsley, chopped',
      '1 tbsp fresh dill, chopped',
      '1 tbsp fresh thyme leaves',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper.',
      'Place cod fillets on the prepared baking sheet.',
      'In a small bowl, combine olive oil and garlic.',
      'Brush the fillets with the garlic oil mixture.',
      'Season with salt and pepper. Top with lemon slices and herbs.',
      'Bake for 15-20 minutes until fish flakes easily with a fork.',
      'Serve hot with additional lemon wedges if desired.',
    ],
    tags: ['dinner', 'seafood', 'high-protein', 'low-carb', 'gluten-free'],
  },
  {
    id: '21',
    name: 'Spinach and Feta Stuffed Chicken Breast',
    image: 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '25 min',
    servings: 4,
    calories: 350,
    protein: 40,
    carbs: 5,
    fat: 18,
    ingredients: [
      '4 chicken breasts',
      '2 cups fresh spinach, chopped',
      '1/2 cup feta cheese, crumbled',
      '2 cloves garlic, minced',
      '1 tbsp olive oil',
      '1 tsp dried oregano',
      '1/2 tsp red pepper flakes (optional)',
      'Salt and pepper to taste',
      '1 tbsp olive oil for cooking',
    ],
    instructions: [
      'Preheat oven to 375°F (190°C).',
      'In a skillet, heat 1 tbsp olive oil over medium heat. Add garlic and sauté for 30 seconds.',
      'Add spinach and cook until wilted, about 2 minutes. Remove from heat and let cool slightly.',
      'Mix spinach with feta cheese, oregano, red pepper flakes, salt, and pepper.',
      'Cut a pocket into each chicken breast, being careful not to cut all the way through.',
      'Stuff each chicken breast with the spinach and feta mixture.',
      'Season the outside of the chicken with salt and pepper.',
      'Heat 1 tbsp olive oil in an oven-safe skillet over medium-high heat.',
      'Sear chicken breasts for 3-4 minutes per side until golden brown.',
      'Transfer skillet to the oven and bake for 15-20 minutes until chicken is cooked through.',
      'Let rest for 5 minutes before serving.',
    ],
    tags: ['dinner', 'high-protein', 'low-carb', 'gluten-free'],
  },
  {
    id: '22',
    name: 'Vegetable Frittata',
    image: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '20 min',
    servings: 6,
    calories: 220,
    protein: 14,
    carbs: 8,
    fat: 16,
    ingredients: [
      '8 large eggs',
      '1/4 cup milk',
      '1 bell pepper, diced',
      '1 zucchini, diced',
      '1/2 onion, diced',
      '1 cup spinach, chopped',
      '1/2 cup cherry tomatoes, halved',
      '1/2 cup feta cheese, crumbled',
      '2 tbsp olive oil',
      '2 cloves garlic, minced',
      '1 tsp dried herbs (thyme, oregano, or Italian seasoning)',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 375°F (190°C).',
      'In a large bowl, whisk together eggs, milk, salt, and pepper.',
      'Heat olive oil in an oven-safe skillet over medium heat.',
      'Add onion and sauté for 2-3 minutes until softened.',
      'Add bell pepper, zucchini, and garlic. Cook for 3-4 minutes.',
      'Add spinach and cook until wilted.',
      'Spread vegetables evenly in the skillet. Pour egg mixture over the vegetables.',
      'Top with cherry tomatoes and feta cheese.',
      'Cook on stovetop for 3-4 minutes until edges start to set.',
      'Transfer skillet to the oven and bake for 15-18 minutes until eggs are set and top is lightly golden.',
      'Let cool for 5 minutes before slicing and serving.',
    ],
    tags: ['breakfast', 'brunch', 'vegetarian', 'low-carb', 'high-protein', 'meal-prep'],
  },
  {
    id: '23',
    name: 'Teriyaki Tofu Stir Fry',
    image: 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '20 min',
    cookTime: '15 min',
    servings: 4,
    calories: 320,
    protein: 18,
    carbs: 35,
    fat: 12,
    ingredients: [
      '1 block (14 oz) extra-firm tofu, pressed and cubed',
      '2 tbsp cornstarch',
      '2 tbsp vegetable oil',
      '1 broccoli head, cut into florets',
      '1 bell pepper, sliced',
      '1 carrot, julienned',
      '1 cup snap peas',
      '3 cloves garlic, minced',
      '1 tbsp ginger, grated',
      'For the teriyaki sauce:',
      '1/4 cup soy sauce',
      '2 tbsp rice vinegar',
      '2 tbsp maple syrup or honey',
      '1 tbsp cornstarch',
      '1/4 cup water',
      '1 tsp sesame oil',
    ],
    instructions: [
      'Press tofu to remove excess water, then cut into cubes.',
      'Toss tofu cubes with cornstarch to coat.',
      'Heat 1 tbsp oil in a large skillet or wok over medium-high heat.',
      'Add tofu and cook for 2-3 minutes per side until golden and crispy. Remove and set aside.',
      'In the same pan, add remaining oil. Add garlic and ginger, cook for 30 seconds.',
      'Add broccoli, bell pepper, carrot, and snap peas. Stir fry for 5-6 minutes until vegetables are crisp-tender.',
      'Meanwhile, whisk together all sauce ingredients in a small bowl.',
      'Return tofu to the pan with the vegetables. Pour sauce over everything.',
      'Cook for 2-3 minutes, stirring frequently, until sauce thickens and coats everything.',
      'Serve hot over rice or noodles.',
    ],
    tags: ['dinner', 'vegan', 'vegetarian', 'asian', 'high-protein'],
  },
  {
    id: '24',
    name: 'Zucchini Noodles with Pesto',
    image: 'https://images.unsplash.com/photo-1556386734-7fa5de232b1d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '5 min',
    servings: 2,
    calories: 280,
    protein: 8,
    carbs: 12,
    fat: 22,
    ingredients: [
      '3 medium zucchini, spiralized',
      '2 tbsp olive oil',
      '2 cloves garlic, minced',
      '1 cup cherry tomatoes, halved',
      '1/4 cup pine nuts, toasted',
      '1/4 cup grated Parmesan cheese',
      'For the pesto:',
      '2 cups fresh basil leaves',
      '1/3 cup pine nuts',
      '2 cloves garlic',
      '1/2 cup olive oil',
      '1/2 cup grated Parmesan cheese',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Make the pesto: In a food processor, combine basil, pine nuts, and garlic. Pulse until coarsely chopped.',
      'With the processor running, slowly add olive oil until smooth.',
      'Stir in Parmesan cheese, salt, and pepper. Set aside.',
      'Heat olive oil in a large skillet over medium heat. Add garlic and cook for 30 seconds.',
      'Add zucchini noodles and cook for 2-3 minutes until slightly softened but still firm.',
      'Remove from heat and toss with pesto sauce.',
      'Add cherry tomatoes and toss gently to combine.',
      'Serve topped with toasted pine nuts and additional Parmesan cheese.',
    ],
    tags: ['dinner', 'vegetarian', 'low-carb', 'keto', 'quick'],
  },
  {
    id: '25',
    name: 'Berry Protein Parfait',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 2,
    calories: 290,
    protein: 20,
    carbs: 30,
    fat: 10,
    ingredients: [
      '2 cups Greek yogurt',
      '2 tbsp honey or maple syrup',
      '1 tsp vanilla extract',
      '1 cup mixed berries (strawberries, blueberries, raspberries)',
      '1/2 cup granola',
      '2 tbsp chia seeds',
      '2 tbsp sliced almonds',
    ],
    instructions: [
      'In a bowl, mix Greek yogurt with honey and vanilla extract.',
      'In two serving glasses or jars, layer yogurt mixture, berries, and granola.',
      'Repeat layers until all ingredients are used, ending with berries on top.',
      'Sprinkle with chia seeds and sliced almonds.',
      'Serve immediately or refrigerate for up to 24 hours (add granola just before serving to keep it crunchy).',
    ],
    tags: ['breakfast', 'snack', 'vegetarian', 'high-protein', 'no-cook'],
  },
  {
    id: '26',
    name: 'Turkey and Vegetable Meatballs',
    image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '20 min',
    cookTime: '25 min',
    servings: 4,
    calories: 320,
    protein: 28,
    carbs: 15,
    fat: 16,
    ingredients: [
      '1 lb (450g) ground turkey',
      '1 zucchini, grated and excess water squeezed out',
      '1 carrot, grated',
      '1/2 onion, finely diced',
      '2 cloves garlic, minced',
      '1/4 cup almond flour',
      '1 egg',
      '2 tbsp fresh parsley, chopped',
      '1 tsp dried oregano',
      '1/2 tsp red pepper flakes (optional)',
      'Salt and pepper to taste',
      '2 tbsp olive oil for cooking',
    ],
    instructions: [
      'Preheat oven to 375°F (190°C). Line a baking sheet with parchment paper.',
      'In a large bowl, combine all ingredients except olive oil. Mix well with your hands.',
      'Form mixture into 16 meatballs, about 1.5 inches in diameter.',
      'Heat olive oil in a large skillet over medium-high heat.',
      'Brown meatballs in batches, about 2 minutes per side.',
      'Transfer browned meatballs to the prepared baking sheet.',
      'Bake for 15-20 minutes until cooked through (internal temperature of 165°F/74°C).',
      'Serve with marinara sauce, on top of zucchini noodles, or in a wrap.',
    ],
    tags: ['dinner', 'high-protein', 'low-carb', 'meal-prep'],
  },
  {
    id: '27',
    name: 'Coconut Curry Lentil Soup',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '30 min',
    servings: 6,
    calories: 310,
    protein: 12,
    carbs: 40,
    fat: 12,
    ingredients: [
      '1 cup red lentils, rinsed',
      '1 onion, diced',
      '2 carrots, diced',
      '3 cloves garlic, minced',
      '1 tbsp ginger, grated',
      '1 tbsp curry powder',
      '1 tsp ground turmeric',
      '1/2 tsp ground cumin',
      '1/4 tsp cayenne pepper (optional)',
      '1 can (14 oz) diced tomatoes',
      '1 can (14 oz) coconut milk',
      '4 cups vegetable broth',
      '2 cups spinach, chopped',
      '2 tbsp lime juice',
      '1/4 cup cilantro, chopped',
      'Salt and pepper to taste',
    ],
    instructions: [
      'In a large pot, heat olive oil over medium heat. Add onion and carrots, sauté for 5 minutes.',
      'Add garlic and ginger, cook for another minute until fragrant.',
      'Stir in curry powder, turmeric, cumin, and cayenne pepper. Cook for 30 seconds to toast the spices.',
      'Add lentils, diced tomatoes, coconut milk, and vegetable broth. Bring to a boil.',
      'Reduce heat and simmer, covered, for 20-25 minutes until lentils are tender.',
      'Stir in spinach and cook until wilted, about 2 minutes.',
      'Add lime juice and season with salt and pepper to taste.',
      'Serve hot, garnished with cilantro.',
    ],
    tags: ['lunch', 'dinner', 'vegan', 'vegetarian', 'high-fiber', 'meal-prep'],
  },
  {
    id: '28',
    name: 'Grilled Portobello Mushroom Burgers',
    image: 'https://images.unsplash.com/photo-1550317138-10000687a72b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '15 min',
    servings: 4,
    calories: 280,
    protein: 8,
    carbs: 30,
    fat: 14,
    ingredients: [
      '4 large portobello mushroom caps, stems removed',
      '2 tbsp balsamic vinegar',
      '2 tbsp olive oil',
      '2 cloves garlic, minced',
      '1 tsp dried thyme',
      '4 whole grain burger buns',
      '4 slices provolone or Swiss cheese (optional)',
      '1 avocado, sliced',
      '1 tomato, sliced',
      'Arugula or lettuce leaves',
      'For the aioli:',
      '1/4 cup mayonnaise (or vegan mayo)',
      '1 clove garlic, minced',
      '1 tsp lemon juice',
      'Salt and pepper to taste',
    ],
    instructions: [
      'In a small bowl, whisk together balsamic vinegar, olive oil, garlic, thyme, salt, and pepper.',
      'Place mushroom caps in a shallow dish and pour marinade over them. Let marinate for at least 10 minutes.',
      'Meanwhile, make the aioli by combining all aioli ingredients in a small bowl.',
      'Preheat grill or grill pan to medium-high heat.',
      'Grill mushrooms for 4-5 minutes per side until tender.',
      'If using cheese, add a slice to each mushroom during the last minute of grilling.',
      'Toast burger buns on the grill for 1-2 minutes.',
      'Spread aioli on buns, then assemble burgers with mushrooms, avocado, tomato, and greens.',
    ],
    tags: ['dinner', 'vegetarian', 'vegan-option', 'burger'],
  },
  {
    id: '29',
    name: 'Shrimp and Avocado Ceviche',
    image: 'https://images.unsplash.com/photo-1604909052743-94e838986d24?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '20 min',
    cookTime: '0 min',
    servings: 4,
    calories: 220,
    protein: 18,
    carbs: 12,
    fat: 12,
    ingredients: [
      '1 lb (450g) cooked shrimp, peeled and deveined, chopped',
      '1/2 cup lime juice (about 4-5 limes)',
      '1 red onion, finely diced',
      '2 tomatoes, diced',
      '1 cucumber, diced',
      '1 jalapeño, seeded and minced',
      '2 avocados, diced',
      '1/4 cup cilantro, chopped',
      '1 tbsp olive oil',
      'Salt and pepper to taste',
      'Tortilla chips for serving',
    ],
    instructions: [
      'In a large bowl, combine shrimp and lime juice. Let sit for 10 minutes.',
      'Add red onion, tomatoes, cucumber, and jalapeño. Stir to combine.',
      'Gently fold in avocados, cilantro, and olive oil.',
      'Season with salt and pepper to taste.',
      'Refrigerate for at least 30 minutes before serving to allow flavors to meld.',
      'Serve chilled with tortilla chips.',
    ],
    tags: ['appetizer', 'seafood', 'no-cook', 'low-carb', 'high-protein'],
  },
  {
    id: '30',
    name: 'Chocolate Peanut Butter Protein Balls',
    image: 'https://images.unsplash.com/photo-1582657118090-af35eefc4e48?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    prepTime: '15 min',
    cookTime: '0 min',
    servings: 12,
    calories: 120,
    protein: 6,
    carbs: 10,
    fat: 7,
    ingredients: [
      '1 cup rolled oats',
      '1/2 cup natural peanut butter',
      '1/4 cup honey or maple syrup',
      '1/4 cup chocolate protein powder',
      '2 tbsp chia seeds',
      '2 tbsp mini chocolate chips',
      '1 tsp vanilla extract',
      'Pinch of salt',
    ],
    instructions: [
      'In a large bowl, combine all ingredients. Mix well until everything is incorporated.',
      'If the mixture is too dry, add a tablespoon of water or milk. If too wet, add more oats.',
      'Roll the mixture into 12 balls, about 1 inch in diameter.',
      'Place on a parchment-lined tray and refrigerate for at least 30 minutes to firm up.',
      'Store in an airtight container in the refrigerator for up to 1 week.',
    ],
    tags: ['snack', 'vegetarian', 'high-protein', 'no-cook', 'meal-prep'],
  },
];

export const mockMealPlan = {
  '2025-06-02': {
    breakfast: { recipeId: '1', name: 'Avocado Toast' },
    lunch: { recipeId: '2', name: 'Greek Salad' },
    dinner: { recipeId: '3', name: 'Chicken Stir Fry' },
    snacks: [{ name: 'Apple', calories: 95 }, { name: 'Greek Yogurt', calories: 150 }]
  },
  '2025-06-03': {
    breakfast: { name: 'Oatmeal with Berries', calories: 280 },
    lunch: { recipeId: '2', name: 'Greek Salad' },
    dinner: { name: 'Grilled Salmon', calories: 420 },
    snacks: [{ name: 'Mixed Nuts', calories: 170 }]
  },
  '2025-06-04': {
    breakfast: { name: 'Smoothie Bowl', calories: 310 },
    lunch: { name: 'Quinoa Bowl', calories: 380 },
    dinner: { recipeId: '3', name: 'Chicken Stir Fry' },
    snacks: [{ name: 'Protein Bar', calories: 200 }]
  }
};

export const mockFoodLog = {
  '2025-06-02': {
    totalCalories: 1890,
    totalProtein: 95,
    totalCarbs: 180,
    totalFat: 75,
    meals: [
      { name: 'Avocado Toast', calories: 320, protein: 12, carbs: 30, fat: 18, time: '08:30', mealType: 'breakfast' as const },
      { name: 'Apple', calories: 95, protein: 0.5, carbs: 25, fat: 0.3, time: '10:30', mealType: 'snack' as const },
      { name: 'Greek Salad', calories: 250, protein: 8, carbs: 15, fat: 20, time: '13:00', mealType: 'lunch' as const },
      { name: 'Greek Yogurt', calories: 150, protein: 15, carbs: 10, fat: 5, time: '16:00', mealType: 'snack' as const },
      { name: 'Chicken Stir Fry', calories: 380, protein: 35, carbs: 25, fat: 15, time: '19:00', mealType: 'dinner' as const },
    ]
  }
};

export const mockGroceryList = [
  { id: '1', name: 'Avocados', category: 'Produce', checked: false },
  { id: '2', name: 'Whole grain bread', category: 'Bakery', checked: true },
  { id: '3', name: 'Eggs', category: 'Dairy', checked: false },
  { id: '4', name: 'Cucumber', category: 'Produce', checked: false },
  { id: '5', name: 'Tomatoes', category: 'Produce', checked: false },
  { id: '6', name: 'Red onion', category: 'Produce', checked: true },
  { id: '7', name: 'Kalamata olives', category: 'Canned Goods', checked: false },
  { id: '8', name: 'Feta cheese', category: 'Dairy', checked: false },
  { id: '9', name: 'Olive oil', category: 'Oils & Vinegars', checked: true },
  { id: '10', name: 'Chicken breast', category: 'Meat', checked: false },
  { id: '11', name: 'Bell peppers', category: 'Produce', checked: false },
  { id: '12', name: 'Broccoli', category: 'Produce', checked: false },
  { id: '13', name: 'Carrots', category: 'Produce', checked: true },
  { id: '14', name: 'Soy sauce', category: 'Condiments', checked: false },
  { id: '15', name: 'Honey', category: 'Baking', checked: false },
];